plugins {
    id 'net.neoforged.moddev' version '2.0.80'
    id 'maven-publish'
    id "me.modmuss50.mod-publish-plugin" version "2.+"
}

sourceCompatibility = JavaVersion.VERSION_21
targetCompatibility = JavaVersion.VERSION_21

archivesBaseName = project.archives_base_name
version = project.minecraft_version + "-NeoForge-" + project.mod_version
group = project.maven_group
var realVersion = project.mod_version + '+neoforge'

neoForge {
    // We currently only support NeoForge versions later than 21.0.x
    // See https://projects.neoforged.net/neoforged/neoforge for the latest updates
    version = project.loader_version

    // Validate AT files and raise errors when they have invalid targets
    // This option is false by default, but turning it on is recommended
    validateAccessTransformers = true

    mods {
        // define mod <-> source bindings
        // these are used to tell the game which sources are for which mod
        // mostly optional in a single mod project
        // but multi mod projects should define one per mod
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }

    runs {
        client {
            client()
            ideName = "Run ${project.mod_id} - Client"
        }
        server {
            server()
            ideName = "Run ${project.mod_id} - Server"
        }
        data {
            data()
            ideName = "Run ${project.mod_id} - Data"
            programArguments.addAll "--mod", "${mod_id}",
                    "--output", file('src/generated/resources/').getAbsolutePath(),
                    "--existing", file('src/main/resources/').getAbsolutePath()
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    maven {
        url "https://maven.su5ed.dev/releases"
    }
    maven { url "https://maven.shedaniel.me/" }
    maven { url "https://maven.terraformersmc.com/releases/" }

    maven { url = "https://mvn.devos.one/snapshots/" }
    maven { url = "https://maven.jamieswhiteshirt.com/libs-release" } // Reach Entity Attributes
//    maven { url = "https://maven.ladysnake.org/releases" } // Cardinal Components API
    maven { url = "https://api.modrinth.com/maven" }
    maven { url = "https://maven.vram.io" }
    flatDir { dir 'libs' }
}

dependencies {
    // Fabric API. This is technically optional, but you probably want it anyway.
    implementation "org.sinytra.forgified-fabric-api:forgified-fabric-api:${project.fabric_version}"

    api("me.shedaniel.cloth:cloth-config-neoforge:${project.cloth_config_version}")

    // https://modrinth.com/mod/kiwi/versions
    implementation(annotationProcessor("maven.modrinth:kiwi:15.5.0+neoforge"))
    // https://modrinth.com/mod/jade/versions
    implementation "maven.modrinth:jade:15.10.0+neoforge"

    compileOnly "maven.modrinth:indypets:1.4.7-1.21"
}

tasks.withType(JavaCompile).configureEach {
    // ensure that the encoding is set to UTF-8, no matter what the system default is
    // this fixes some edge cases with special characters not displaying correctly
    // see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
    // If Javadoc is generated, this must be specified in that task too.
    it.options.encoding = "UTF-8"

    // Minecraft 1.18 (1.18-pre2) upwards uses Java 17.
    it.options.release = 21
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    exclude("/assets/${project.mod_id}/lang/en_us.existing.json")
    exclude '**/*.bat'
    /*
    from("LICENSE") {
        rename { "${it}_${project.archivesBaseName}"}
    }
    */
}

// configure the maven publication
publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
        // Notice: This block does NOT have the same function as the block in the top level.
        // The repositories here will be used for publishing your artifact, not for
        // retrieving dependencies.
    }
}

publishMods {
    file = jar.archiveFile
    changelog = file('CHANGELOG.md').exists() ? file('CHANGELOG.md').text : ''
    type = ['release': STABLE, 'beta': BETA, 'alpha': ALPHA][release_type]
    modLoaders.add("neoforge")
    displayName = "[NeoForge ${supported_version}] ${mod_version}"
    version = realVersion

    curseforge {
        projectId = "559989"
        client = true
        server = true
        accessToken = providers.environmentVariable("CURSE_TOKEN")
        minecraftVersions.add(minecraft_version)
        requires("kiwi")
        optional("cloth-config")
    }
    modrinth {
        projectId = "4w0EzGRW"
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")
        minecraftVersions.add(minecraft_version)
        requires("kiwi")
        optional("cloth-config")
    }
}