# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G -Xms3G
org.gradle.daemon=false

# Fabric Properties
# check these on https://fabricmc.net/develop/
minecraft_version=26.1.2
supported_version=26.1.X
archive_minecraft_version=26.1
loader_version=0.19.3
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=26.0.5
release_type=release
mod_id=companion
maven_group=snownee.companion
archives_base_name=Companion

# Dependencies
fabric_api_version=0.150.0+26.1.2
# https://modrinth.com/mod/cloth-config/versions
cloth_config_version=26.1.154
modmenu_version=18.0.0-beta.1
kiwi_version=26.0.4
rei_version=9.1.574
# https://github.com/Fabricators-of-Create/Create/blob/mc1.21.1/fabric/dev/gradle.properties
port_lib_version=2.3.5-beta.33+1.20.1
port_lib_modules=accessors,base,entity,extensions,networking,obj_loader,tags,transfer,models,tool_actions,client_events,brewing,config
cca_version=5.0.1
reach_entity_attributes_version=2.3.0
