# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G -Xms3G -DsocksProxyHost=127.0.0.1 -DsocksProxyPort=1079
org.gradle.daemon=false
# org.gradle.java.home=D:/Program Files/Eclipse Foundation/jdk-17.0.1.12-hotspot

# Fabric Properties
# check these on https://fabricmc.net/versions.html
minecraft_version=1.20.1
supported_version=1.20.1
loader_version=0.16.14

# Mod Properties
mod_version=5.2.2
release_type=beta
mod_id=companion
maven_group=snownee.companion
archives_base_name=Companion

# Dependencies
fabric_version=0.92.5+1.20.1
# https://modrinth.com/mod/cloth-config/versions
cloth_config_version=11.1.118
modmenu_version=7.0.0
kiwi_version=11.8.29
rei_version=9.1.574
# https://github.com/Fabricators-of-Create/Create/blob/mc1.20.1/fabric/dev/gradle.properties
port_lib_version=2.3.5-beta.33+1.20.1
port_lib_modules=accessors,base,entity,extensions,networking,obj_loader,tags,transfer,models,tool_actions,client_events,brewing,config
cca_version=5.0.1
reach_entity_attributes_version=2.3.0
