modLoader="javafml"
loaderVersion="[41,)"
license="ARR"

[[mods]]
modId="companion"
version="${file.jarVersion}"
displayName="Companion"
authors="Snownee"
displayURL="https://www.curseforge.com/minecraft/mc-mods/companion"
description="Protect your pets."

[[dependencies.companion]]
    modId="kiwi"
    mandatory=false
    versionRange="[11,)"
    ordering="NONE"
    side="BOTH"

[modproperties.companion]
    catalogueItemIcon="bone" #Support for Catalogue mod
